package mx.itson.pregunta2.ui;

import mx.itson.pregunta2.entidades.Respuesta;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.sql.Date;

// Falta agregar la fecha de la respuesta, Andrés

/**
 * Interfaz de usuario para agregar o editar un objeto de tipo respuesta.
 *
 * @author Andrés Uriel López Castillo
 * @author Diego Castro Arce
 */
public class RespuestaFormulario extends javax.swing.JDialog {
  /** Id de la pregunta. */
  int idPregunta = 0;

  /** Id de la respuesta. */
  int id = 0;

  /** Fecha de creación. */
  Date fechaCreacion = new Date(System.currentTimeMillis());

  /** El estado de la pregunta. */
  String estado = "";

  /** Instancia para inicializar componentes. */
  public RespuestaFormulario() {
    initComponents();
  }

  /**
   * Instancia para agregar o editar una pregunta.
   *
   * @param parent El componente padre
   * @param modal Indica si el formulario es modal
   * @param idPregunta Id de la pregunta
   */
  public RespuestaFormulario(java.awt.Frame parent, boolean modal, int idPregunta) {
    super(parent, modal);
    this.idPregunta = idPregunta;
    initComponents();

    cargarFormulario();
  }

  /**
   * Instancia para comprobar el estado de la pregunta.
   *
   * @param parent El componente padre
   * @param modal Indica si el formulario es modal
   * @param idPregunta Id de la pregunta
   * @param estado Estado de la pregunta
   */
  public RespuestaFormulario(java.awt.Frame parent, boolean modal, int idPregunta, String estado) {
    super(parent, modal);
    this.idPregunta = idPregunta;
    this.estado = estado;
    initComponents();
  }

  /** Obtiene el valor de respuesta. */
  public void cargarFormulario() {
    if (this.id != 0) {
      Respuesta r = Respuesta.obtenerPorId(this.id);
      txtRespuesta.setText(r.getRespuesta());
    }
  }
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblTitulo = new javax.swing.JLabel();
    lblRespuesta = new javax.swing.JLabel();
    txtRespuesta = new javax.swing.JTextField();
    btnAgregar = new javax.swing.JButton();

    lblTitulo.setText("Nueva respuesta");

    lblRespuesta.setText("Respuesta");

    btnAgregar.setText("Agregar");
    btnAgregar.addActionListener(
        new java.awt.event.ActionListener() {
          public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAgregarActionPerformed(evt);
          }
        });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout
                                    .createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(btnAgregar))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtRespuesta)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addComponent(lblRespuesta)
                                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap())
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addGap(0, 144, Short.MAX_VALUE)
                    .addComponent(lblTitulo)
                    .addGap(144, 144, 144)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitulo)
                    .addGap(18, 18, 18)
                    .addComponent(lblRespuesta)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(
                        txtRespuesta,
                        javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(btnAgregar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    pack();
    setLocationRelativeTo(null);
  } // </editor-fold>//GEN-END:initComponents

  private void btnAgregarActionPerformed(
      ActionEvent evt) { // GEN-FIRST:event_btnAgregarActionPerformed
    String respuesta = txtRespuesta.getText();

    boolean resultado =
        this.id == 0
            ? Respuesta.guardar(respuesta, fechaCreacion, idPregunta)
            : Respuesta.editar(this.idPregunta, fechaCreacion, respuesta);

    if (resultado) {
      JOptionPane.showMessageDialog(
          this,
          "El registro fue guardado correctamente",
          "REGISTRO GUARDADO",
          JOptionPane.INFORMATION_MESSAGE);
      dispose();
    } else {
      JOptionPane.showMessageDialog(
          this, "Ocurrió un error al guardar el registro", "ERROR", JOptionPane.ERROR_MESSAGE);
      dispose();
    }
  } // GEN-LAST:event_btnAgregarActionPerformed

  /**
   * Main de la interfaz de usuario.
   *
   * @param args Los argumentos de la línea de comandos.
   */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
          javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(RespuestaFormulario.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(RespuestaFormulario.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(RespuestaFormulario.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(RespuestaFormulario.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(
        new Runnable() {
          public void run() {
            RespuestaFormulario dialog =
                new RespuestaFormulario(new javax.swing.JFrame(), true, 0, "");
            dialog.addWindowListener(
                new java.awt.event.WindowAdapter() {
                  @Override
                  public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                  }
                });
            dialog.setVisible(true);
          }
        });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAgregar;
  private javax.swing.JLabel lblRespuesta;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JTextField txtRespuesta;
  // End of variables declaration//GEN-END:variables
} // Fin de la clase RespuestaFormulario
